### ISSUE TITLE
Machine-Readable List of ACA Preventive Procedure Codes

### ISSUE THREAD

**Issue by HeatherBrotsos** [demand-driven-open-data/ddod-intake#44]
I am looking for a complete list of all procedure codes associated with preventive services covered under ACA.

**Comment by dportnoy** [comment]
Thanks for entering your request.  Could you provide more background and relevant links as a starting point.  Is this for Medicare FFS, Medicare Advantage, Medicaid?  Is this related to requirements for plans on the federal insurance marketplace?

Is it just a list of CPTs?  Are there other relevant fields?  How frequently does the data change?

**Comment by HeatherBrotsos** [comment]
What I need are the services covered by private insurance plans and required by ACA here: https://www.healthcare.gov/preventive-care-benefits/

The key pieces of information that I have thought of are:
CPT Code
Diagnosis code, if applicable
Any other restrictions, (e.g. age requirement, pregnant women, etc.)
Date effective

There are sporadic updates to this list, but I believe plans are required to update their coverage to reflect any changes annually.

**Comment by dportnoy** [comment]
@HeatherBrotsos  Thanks!  We'll get that going.  To structure this request as a Use Case (such as http://hhs.ddod.us/wiki/Use_Cases), can you describe how this data will be used and the value it delivers.

**Comment by HeatherBrotsos** [comment]
Value: provides a standard source of preventive services that are covered by private insurance plans for free under ACA 
Data will be used to examine whether patients are being charged copayments or deductibles for claims filed with qualifying services

**Comment by dportnoy** [comment]
@HeatherBrotsos Looks like you're referring specifically to FFMs/QHPs, rather than other private plans such as those via Medicare Advantage.  Is that right?  If not, can you provide any additional references to preventive coverage outside of FFMs?

**Comment by dportnoy** [comment]
Entry for specifications created: http://hhs.ddod.us/wiki/Use_Case_44
@HeatherBrotsos Feel free to edit.  Simply sign on with any Google account.

**Comment by HeatherBrotsos** [comment]
Yes, that's correct.  Thanks!

**Comment by dportnoy** [comment]
Update.  Waiting to hear back from internal channels.

**Comment by betshsu** [comment]
@HeatherBrotsos David scraped the file here for preventive services CPT files: https://www.cms.gov/Medicare/Prevention/PrevntionGenInfo/Downloads/MPS_QuickReferenceChart_1.pdf and created json, txt, and xlsx files.  You can find them on healthdata.gov here: http://www.healthdata.gov/dataset/ddod-use-case-measure-coverage-preventive-care-ffm-insurance-plans (they are also linked to on the wiki entry for this use case under the "solution" section).  The caveat is that there are the preventive services CPT codes for Medicare.  David followed up with CMS, and it appears that they are not prescriptive toward QHPs, so QHPs may or may not use these same codes.  

Edit: I have temporarily taken down the healthdata.gov entry, but hopefully will be able to put it back up in the near future.

Can you let us know if this meets your needs?  Thanks.

**Comment by HeatherBrotsos** [comment]
Thanks for the quick turnaround.  This looks great for Medicare covered services and will definitely be useful.  There are some distinctions between what is covered by Medicare versus private insurance plans that must now comply with ACA.  For example, services provided specifically to children are not included in the Medicare list.  Unfortunately, there doesn't appear to be one single source of all service codes that are now covered.

**Comment by betshsu** [comment]
Unfortunately, we don't believe there is a definitive source for private insurance plans.  @DavidXPortnoy can brief based on his discussion with CMS.

**Comment by HeatherBrotsos** [comment]
After some extensive searching, I finally found a list from CDC with all the codes!  http://www.cdc.gov/prevention/billingcodes.html

**Comment by betshsu** [comment]
That's awesome.  I guess I can stop reading the UHC and Cigna documentation now...

Do you still need the codes in a machine-readable format?

**Comment by HeatherBrotsos** [comment]
Well if you have a better idea than what I'm going to do manually, I am all ears.

**Comment by betshsu** [comment]
ha... well, we can contact CDC to see if there is a more user-friendly file format for the info on the website, but otherwise, we'd probably do something similar to what you will end up doing.  If you do manage to convert the info into a more user-friendly format, it would be great if you'd be willing to share that back with the community.

I assume you noticed the disclaimer at the top of the CDC that it might not be a comprehensive list of all codes used by all insurers?  We did get confirmation from CMS that they do not have a definitive list of preventive services CPT codes; I will update the wiki accordingly.

**Comment by marks** [comment]
+1 @betshsu - The CDC has an open data portal at data.cdc.gov that the dataset should really live on so it has machine readable download links and APIs

**Comment by betshsu** [comment]
Thanks @marks.  I'll see if I can find it there and post the link if so; since it's not CDC-originated data, I'm not sure if it will be in their data catalog.

**Comment by marks** [comment]
@betshsu it wouldnt be on there but it definitely should be!

**Comment by betshsu** [comment]
@marks Oh, sorry, I misread your comment -- I read it as it "should be on there"

**Comment by dportnoy** [comment]
There might be other ways to obtain CPT codes actually in use by QHPs.  The data most likely exists within CMS/CCIIO collected for the risk adjustment submissions.  It remains to be determined whether its possible to get a hold of aggregated, de-identified CPT data.  

"Risk adjustment data will include ... enrollee claims and encounter data that resulted in a payment to institutional and medical providers."  Source: https://www.cms.gov/CCIIO/Resources/Files/Downloads/payment-notice-3-11-2013.pdf and https://www.cms.gov/CCIIO/Resources/Regulations-and-Guidance/

**Comment by HeatherBrotsos** [comment]
That's an interesting angle, which I think would produce some great insights.  A defined list of codes that they should be using is still of interest too.  I'm working on converting the information I found from CDC into a format conducive to analysis and I'll share that once I have something.

**Comment by betshsu** [comment]
We just received an Excel version of what is on the CDC website.  I would like to verify it against the various sources they scraped the data from and then hopefully get permission to share it publicly.

**Comment by HeatherBrotsos** [comment]
That’s great news!  It would be great to work from an official HHS version.  In the meantime, I copied the codes into a .csv file and have begun the process of transforming the ranges into an itemized list.  I was going to post back here when complete, but here is the work in progress: https://github.com/HeatherBrotsos/ACA-Preventive-Services/tree/master/data

The first is a direct copy of the information on the CDC site and the second introduces some additional information that is relevant for analysis, such as the effective date of coverage for a service and additional restrictions.  I’ll update you once I have the .csv of all the itemized codes in a format ready for analysis.

**Comment by betshsu** [comment]
Thanks for posting; I think your version will have more information than the CDC version (which is really just what is on the website), but I will go ahead and verify the file we received from CDC and adjust the formatting to make it a bit friendlier and then post.

**Comment by betshsu** [comment]
@HeatherBrotsos I have uploaded the Excel and text files I received from CDC here: https://github.com/betshsu/DDOD-use-case-44; in addition, I also uploaded the pdfs that were used as the source files for the codes.

The format in the CDC Excel file mirrors what is on the website, so it is not the most friendly for analytic purpose.  In the repo, there is a "billing codes modified" Excel file where I transformed the format for two services into a more relational table as an example.  Not sure if this would be more useful for you, and it does take some work because of the ranges used in the various codes.

**Comment by HeatherBrotsos** [comment]
This is awesome!  Especially appreciate all the source documents.  Documenting what codes apply to each service seems to be one of the hardest parts!  

We are definitely thinking along the same lines.  See here for my attempt to convert the ranges into a list of all codes: https://github.com/HeatherBrotsos/ACA-Preventive-Services  
As I'm sure you know, the structure of these codes makes it particularly challenging to accurately transform the ranges.  What I've got is still a starting point - have not attempted a thorough QC on this and there is plenty of room for error.  It would be great to continue collaboration on this.

**Comment by betshsu** [comment]
Agreed, the data gets complicated quickly, and the only QC I have done so far is to make sure the Excel file matched what was on the CDC website, since CDC indicated that there was a possibility that changes had been made directly to the html that were not reflected in the Excel file.

Just an FYI, I am still looking at whether we can publish the Medicare CPT codes -- there are potential copyright issues involved, but I'm contacting the copyright owners to see what they will allow.  But it may be that we won't be able to put those files back up; will update when I know more.

**Comment by dportnoy** [comment]
@HeatherBrotsos Thanks for publishing that repo!

**Comment by betshsu** [comment]
Updated wiki with info regarding definitive list of preventive service codes covered by private insurance plans and issues regarding publishing alternate data formats due to AMA licensing of CPT codes.

@HeatherBrotsos if you've made any progress with transforming the CDC data, let us know.  Thanks!

**Comment by dportnoy** [comment]
Closing, since solution to original request has been provided.  If in the future AMA licensing allows hosting CPT codes in additional locations, links will be posted here.
