### ISSUE TITLE
2015 Rate PUF data incomplete

### ISSUE THREAD

**Issue by svidyan** [demand-driven-open-data/ddod-intake#50]
I noticed that the 2015 Rate PUF data does not contain rates for sources from SERFF and OPM. It contains only rates information for source from HIOS. 

While the Plan Attributes PUF for 2015 contains all data from sources SERFF, OPM and HIOS.

I am now having difficulty getting the rates for plans that have a source of SERFF or OPM.

Please let us know if this issue will be fixed or is there a different API access to PUF rates data from SERFF and OPM sources.

**Comment by betshsu** [comment]
Hi @svidyan, thanks for your entry.  Have you already contacted the help email for the Marketplace PUF and not gotten a response?  Just wanted to check before doing any inquires.  Just to clarify, we are not the direct data owners for any of the HHS data.  Thanks.

Edit to clarify: We can definitely help you pursue this; just trying to gather info on whether you've already contact CMS and what kind of response you might have gotten before reaching out internally.

**Comment by svidyan** [comment]
Thanks for your message. Yes, I have contacted the hep email and did not
get a response to my question. It was a general purpose response.

Regards,
Sri

**Comment by betshsu** [comment]
Good to know, thanks.  We'll start looking into this and see what headway we can make in understanding why there are differences in the data and what can be done to resolve them.  To clarify, have previous years rate PUFs contained sources from SERFF and OPM and this is change in the 2015 data?

**Comment by betshsu** [comment]
Created the wiki entry here: http://hhs.ddod.us/index.php?title=Use_Case_50

@svidyan Can you either edit the wiki or post here with how you will be using the data?  Also feel free to add further specifications, etc.  Thanks.

**Comment by betshsu** [comment]
@svidyan Sorry for the delay in following up while we were waiting for an update on data use and specifications from you.  

I wanted to check in on how you were trying to load the 2015 Rate PUF data.  I have finally gotten around to downloading and loading the Rate PUF data and don't see an issue with OPM or SERFF plans missing from the "SourceName" field.  However, in order to load the full dataset, I have to use a program other than Excel; the full dataset does not load in Excel because of size, so I only see HIOS plans in Excel.  However, I haven't worked with the Marketplace PUFs before, so I might be incorrect in my interpretation of the data and what data fields you are looking for.   Thanks.

**Comment by betshsu** [comment]
@svidyan checking in again on the question above.  Thanks.

**Comment by svidyan** [comment]
I believe the 2016 data looks fine. I am able to retrieve HIOS, SERFF and
OPM data.
Thanks for looking into this.

Sri

**Comment by betshsu** [comment]
Great thanks for confirming.  If you still need the 2015 data, you should try downloading the file again -- it may have been updated since you first downloaded, as I am able to see SERFF and OPM data in it.
