### ISSUE TITLE
Comparing Drug Coverage across Marketplaces

### ISSUE THREAD

**Issue by ghost** [demand-driven-open-data/ddod-intake#52]
We have been been looking at drug coverage in the various marketplaces, but have been hampered by both missing URLs and incorrectly entered information.  How can we get more plans to submit and/or update their URLs.  This is compulsory information, right?

Will the PUF update throughout the year with updates/fixes?

Does anyone verify the URLs?

**Comment by dportnoy** [comment]
@BAP-Jeff  Would you provide a link to the data you're using and a couple examples that illustrate the issues you describe.  Thanks.

**Comment by ghost** [comment]
Sure thing.

The PUF is located here -[https://www.cms.gov/cciio/resources/data-resources/marketplace-puf.html]

From this page, you will find a link to - [http://download.cms.gov/marketplace-puf/2016/machine-readable-url-puf.zip] The zip file expands to an XLSX file.

I have uploaded the file to my database and pulled an extract for you.  See the attached XLSX file [URLIssues.xlsx](https://github.com/demand-driven-open-data/ddod-intake/files/123594/URLIssues.xlsx).  You will see the "NOT SUBMITTED" records in the "NotSub" tab.

Then the second issue concerning plans that did submit URLs, but they were "Bad" in some way is illustrated in the attached on tab "BadURL.  I have corrected several URLs
- switching https to http, or adding an index.json to the URL.  I can capture that more thoroughly if you like.

While both issues are important, I believe the group of plans that didn't submit is a higher priority.

Thanks,

Jeff

**Comment by ghost** [comment]
You will see that a contact is provided in some cases.  I started hitting up a few of the people listed to see if they had an updated URL.

Got this from Molina:  http://stg-oh-medicaid.molinahealthcare.com/JSON/index.json

**Comment by dportnoy** [comment]
@BAP-Jeff, Seems you have identified some legitimate problems.  Yes, I do believe that the information in these files is mandatory for plans participating on FFMs.  

Could you give us some background in terms of how you want to use the drug formularies.  (In the language of DDOD, this would be the “use case”.)  Knowing this would help us resolve the request.  We can then start the process of investigating the issues identified.

Also, go ahead and say more about the editing of actual URLs (switching https / http, adding index.json, etc.)

**Comment by ghost** [comment]
David,

Thanks for taking a look.  My firm is looking to make comparisons of tier status across a variety of Branded Drugs.  Additionally, we would want to see if there are any differences in the access to these drugs through the use of prior authorizations, quantity limits or steps.  We would like to be able to display geographic/medal level differences (or lack there of) in the branded market

A lot of attention is being paid to the Plan Attributes file, but while that is very important, if you don't know what the actual access to the drugs are, you are missing a critical piece.  We would be happy to share our insights with others when we get the complete file.

I will update that spreadsheet another tab - "Fixes" - and get that back to you hopefully tomorrow.  There are only 5 or 6.

Thanks,

Jeff

**Comment by ghost** [comment]
David,

This might be helpful [https://www.cms.gov/CCIIO/Resources/Data-Resources/Downloads/Disclaimer_for_Machine_Readable.pdf](url).

It states that the data will not only be provided, but will be updated monthly.

Jeff

**Comment by dportnoy** [comment]
@BAP-Jeff, thanks for the explanation.  We'll investigate with the program owners and see what could be reported back.  

Thanks for offering to share your insights!  Hopefully, it could be a great resource for the community.  

A side question for you...  How straight forward is it to compare tier status across plans?  I thought that the actual benefit design and naming varies widely, so it's hard to compare apples to apples.

**Comment by ghost** [comment]
Regarding the side question, CMS's spec forces the plans to abandon numbered tiers and standardize on just a few common tier names (i.e. GENERIC, PREFERRED-BRAND).  CMS also forces the plans to provide standard Drug IDs (from RXNORM).  Both of these decisions make it easy to compare drugs in an apples to apples way.

**Comment by dportnoy** [comment]
@BAP-Jeff, update... Waiting to hear back from program owners.

**Comment by ghost** [comment]
I still owe you that update on the URLs that I fixed by hand...it is going to take me to Friday given my current travel.

Thanks for jumping on my issue!

**Comment by ghost** [comment]
Here is the updated Excel file with the list of URLs I fixed by hand.

[URLIssues.xlsx](https://github.com/demand-driven-open-data/ddod-intake/files/126549/URLIssues.xlsx)

**Comment by dportnoy** [comment]
@BAP-Jeff Thanks for the Excel file.  That was helpful.  I got some preliminary feedback from the program owners this morning, but still waiting for them to send me additional clarifying info.  Stay tuned.

**Comment by dportnoy** [comment]
@BAP-Jeff Apologies for the delay.  Still waiting for some confirmations from program owners.  I've also created a crawler that might be helpful for everyone in the future.

**Comment by ghost** [comment]
Thanks for the update....

Re: Crawler...that makes two of us then ;-) ... I shielded you from some of the other funkiness with the URLs.  If you crawl the initial URLs and then hit all the branches, you'll see some other fun stuff, that needs fixing but I thought I would leave my first round to what seemed like the highest priority items.

**Comment by dportnoy** [comment]
@BAP-Jeff  Do you have code you wouldn't mind sharing for the crawling?  I've only been able to set aside small periods of time to the endeavor.  (In addition to addressing your use case, I'd like to be able to provide more complete datasets for a [Bayes Hack](http://bayeshack.org/) challenge we've designed.  It's coming up in April.)

**Comment by ghost** [comment]
Oh no share it...no problem.  I run this from inside our jenkins instance, but here is the guts of the python script that runs.  I am focussed on the formularies so that is what I pull down specifically.

If there is something specific you want let me know.  If you need help on the challenge just hit me up at jeff@breakawaypartners.com.

You will see the script is made to hit a database, but we/you could redirect that to a file easily.  Again, just ask for some help if you need a specific task run.

[GetHIX.py.zip](https://github.com/demand-driven-open-data/ddod-intake/files/138547/GetHIX.py.zip)

**Comment by ghost** [comment]
David,

I just went out and checked the Marketplace PUF file and looks like it was updated on the 22nd.  It is much better than before.  I will updated you when I run through the crawl over the weekend.

We went from 196 NOT SUBMITTEDs to 18!!  See the list below of NOT SUBMITTERs.  Really just one company.

Thanks for getting on them,

Jeff

# State, IssuerID, IssuerName

FL, 48121, Cigna Health and Life Insurance Company
AL, 17540, Guardian Life Insurance Company of America
WI, 69589, Guardian Life Insurance Company of America
TN, 90402, Guardian Life Insurance Company of America
OK, 81457, Guardian Life Insurance Company of America
NE, 98048, Guardian Life Insurance Company of America
MT, 62818, Guardian Life Insurance Company of America
IA, 50730, Guardian Life Insurance Company of America
AZ, 17454, Guardian Life Insurance Company of America
KS, 61779, Guardian Life Insurance Company of America
OH, 59401, Managed DentalGuard, Inc.
TX, 12846, The Guardian Life Insurance Company
DE, 90955, The Guardian Life Insurance Company
SC, 84939, The Guardian Life Insurance Company
MO, 48786, The Guardian Life Insurance Company
NH, 24847, The Guardian Life Insurance Company
ME, 69227, The Guardian Life Insurance Company
WV, 96480, The Guardian Life Insurance Company

**Comment by dportnoy** [comment]
@BAP-Jeff  Not sure I can take the credit.  The program owners were already working on the cleanup and are using their own quality reporting metrics.  I'll run my code against the new dataset as soon as I get a chance and we can compare notes.

**Comment by ghost** [comment]
David,

I wanted to continue to share with you what I am finding in the data.  As I mentioned I am primarily interested in the HIX formulary.  As such I have extracted the information from the JSON documents and uploaded it to our RedShift instance.  I wanted to start with some Quality Checks.  There are a number of issues in the files, for instance, wrong RXCUIs being used (looks like NDC), very long drug names (think 1560 characters for a few), crazy drug statuses, incorrectly spelled drug statuses....Should I open a new issue or should we just continue with this thread?

Here is an example of some interesting things to look at/share with others.  Specifically looking at drug status, I wanted to see what the distribution looked like.  

[HIXStatus.xlsx](https://github.com/demand-driven-open-data/ddod-intake/files/155281/HIXStatus.xlsx)

Advice on next steps would be great.

Enjoy,

Jeff

**Comment by dportnoy** [comment]
@BAP-Jeff  Thanks for the analysis.  No need to open a separate issue.  Let's keep the conversation here.  I'm waiting until next week to hit up the program owners again, due to their core commitments.

In the mean time, perhaps you could educate me (and others) a bit more on this topic.  I'd like to have a good feel for what range of values would have been expected versus actually observed.  For example...
1. Your spreadsheet of aggregated data shows 106 different statuses.  What collection of values were you expecting?  (I see that https://github.com/CMSgov/QHP-provider-formulary-APIs gives examples of: GENERIC, PREFERRED-GENERIC, NON-PREFERRED-GENERIC, SPECIALTY, BRAND, PREFERRED-BRAND, NON-PREFERRED-BRAND, ZERO-COST-SHARE-PREVENTIVE, MEDICAL-SERVICE.)  
2. Some values are clearly near-identical permutations.  Which ones do you find most perplexing?  Does 
   GENERIC-BRAND make sense?
3. Can you elaborate on what you're seeing with RxCUI vs what's expected?  How many of the values are not valid RXNORM IDs?
4. Any other data significant quality concerns to be raised?  Are the aggregate values in line with expectations?

cc:  @DamonDavis

**Comment by ghost** [comment]
David,

Thanks for taking a look.
1. I believe the API documentation provides a solid list of values that
   everyone should be able to use.  The overall aim (I believe) is to create
   an apples to apples comparison between plan formularies.  As such, I think
   they should be locked into a list of acceptable values.  I updated my
   spreadsheet with another worksheet that lists what I think the status
   should be.  In most cases there is just inconsistency in the names being
   used, either a misspelling or making it plural.  Just want some consistency.
2. See spreadsheet...What might also be helpful for this analysis is to
   flip the analysis around and see what Plans are providing the most
   inconsistent statuses relative to others.  For instance it looks like
   Aetna, CIGNA and UHC, are very consistent.  I suspect the smaller plans are
   the ones struggling a bit.  Let me know if you think that would be
   helpful.  Your program owners could maybe speak to just a few plans versus
   blasting something out to everyone.
3. Regarding NDC usage.  Looks like the HIOS ID - 87416 - Common Ground
   Healthcare Coop is the only Plan submitting NDCs.  ID 47342 - Health
   Tradition Health Plan is submitting a few odd 8 digit drug ids.  Not sure
   what those are.  The bigger issue that I only just know discovered is the
   high number of records that are coming through with NO DrugID at all.  I
   added a list of the drugs and the list of plans that are submitting them.
4.  In aggregate things do look good to me, but I will need to keep looking
   a bit.  One thing that jumped out at me is that in the JSON spec the
   program owners state the the prior_auth, quantity_limit (the restrictions)
   values are optional.  I believe their intention is that they understanding
   not every drug will have that value, so one doesn't need to provide a
   value.  But I believe the unintended consequence is that some plans have
   completely left PA and QLs out.

I have found a few very strange characters in the JSON documents and they
seem to be exclusively in the drugName field.  I don't have an example at
my fingertips, but I will take a look.

Thanks,

Jeff

**Comment by ghost** [comment]
Hmm I don't see the spreadsheet I had attached.

Here it is.

[HIXStatus.xlsx](https://github.com/demand-driven-open-data/ddod-intake/files/159201/HIXStatus.xlsx)

**Comment by dportnoy** [comment]
@BAP-Jeff 
- Yes, I think it would be helpful if you could provide a list of plans struggling with consistency in drug tier naming (per question # 2).
- For the entries missing drug IDs, is this an accurate summary...  Approximately 3% of entries are missing drug IDs (~900K entries out of ~33,600K total).  This issue impacts 5K unique drug names from 31 plans.  
- I requested an update to the schema instructions for prior_authorization and quantity_limit fields: https://github.com/CMSgov/QHP-provider-formulary-APIs/issues/25.

Stay tuned for more.

cc: @DamonDavis

**Comment by ghost** [comment]
@dportnoy 
- I will work on creating the list of companies
- For missing drug IDs that sounds right

And if I was king...I would require that the plans put a date in the JSON documents for last update date.  Not the entire document just in the header.  They are suppose to update these documents monthly.  I am getting a sense that rule is not being followed.

But again overall, this is quite an achievement.  I will soon be looking at the Facilities and Physicians files...

**Comment by dportnoy** [comment]
>  _**The text below contains answers to most of the questions posed in this use case.  It was compiled from conversations and correspondence with the CMS/CCIIO program owners of MR PUF.  While best effort was made to confirm accuracy, at this time this text is not officially confirmed by CMS.**_

## Data quality, validation, compliance
-   The Compliance group within CMS/CCIIO is responsible for overseeing the daily crawl of plan and formulary sites.  (This data is aggregated for use with internal and 3rd party tools.)
-   At the moment, Compliance checks the existence of links and Plan data.  They don’t do any checks on the formulary data.
-   CCIIO reviews and takes action on a “tracking report” produced by the Compliance group once a week.  They then take appropriate action to try getting the issuer in compliance, which may include providing technical assistance.
-   FFM QHP landscape files could be used as a cross-reference.  Health and dental datasets for researchers and issuers are located at [https://www.healthcare.gov/health-and-dental-plan-datasets-for-researchers-and-issuers/](https://www.healthcare.gov/health-and-dental-plan-datasets-for-researchers-and-issuers/)
-   Dental plans are not expected to have formulary data

<br/> 

## Update frequency of MR PUF
-   If the number of changes submitted by issuers is deemed as significant, a new PUF will be generated and uploaded to the [https://www.cms.gov/CCIIO/Resources/Data-Resources/marketplace-puf.html](https://www.cms.gov/CCIIO/Resources/Data-Resources/marketplace-puf.html) page.  This file gets updated less frequently as we get farther away from the enrollment period, since issuers are not making new submissions often.   _(Still trying to find out if there’s a specific number of changes that triggers a new file.)_

<br/> 

### Data included in MR PUF
-   In terms of FFM vs SPMs, for plan year 2016, MR PUF includes:
  -   19 FFM states: Alabama, Alaska, Arizona, Florida, Georgia, Indiana, Louisiana, Mississippi (individual market), Missouri, New Jersey, North Carolina, North Dakota, Oklahoma, Pennsylvania, South Carolina, Tennessee, Texas, Wisconsin, Wyoming
  -   15 SPM states: Arkansas (individual market), Delaware, Iowa, Illinois, Kansas, Maine, Michigan, Montana, Nebraska, New Hampshire, Ohio, South Dakota, Utah (individual market), Virginia, West Virginia  
-   Only issuers with on-exchange plans (that is, no off-exchange only issuers)  

<br/> 

### Data excluded from MR PUF
-   MR PUF excludes SBM or SBM-FP (SBM-FPs are SBMs that rely on the federal information technology platform for QHP eligibility and enrollment functionality) issuers.  For plan year 2016, MR PUF excludes:
  -  18 SBM states: Arkansas (SHOP market), California, Colorado, Connecticut, District of Columbia, Hawaii (SHOP market), Idaho, Kentucky, Maryland, Massachusetts Minnesota, Mississippi (SHOP market), New Mexico (SHOP market), New York, Oregon (SHOP market), Rhode Island, Utah (SHOP market), Vermont, Washington)
  -  4 SBM-FP states: Hawaii (individual market), Nevada, New Mexico (individual market), Oregon (individual market).   _(Still need to confirm if these will these be made available at a later date.)_
    <br/> <br/> 
-   Issuer IDs which are certified but temporarily or permanently “unavailable” on the marketplace right now are not included. 
  -  This can happen for a variety of reasons, including (but not necessarily limited to):
    -  Being closed to new enrollments at the request of the state
    -  Being suppressed because of bad data on HealthCare.gov
  -  Currently there’s not a list of issuers that are active in the marketplace (ie, have enrollment for 2016) but “unavailable” in the MR PUF file.  (Such a list might be made available at a later date.)
    <br/> <br/> 
-   There are about 200 issuers that have not submitted anything at all or withdrew from the marketplace entirely.  This list is not currently available from CMS.  

<br/> 

### Naming of the drug tiers
-   Currently, there is no drug tier naming taxonomy being enforced.  Originally there was a lot of discussion as to whether to mandate a naming convention (e.g., 1, 2, 3 vs. generic, brand).  But the end, it was decided to keep it open ended for now, due to lack of consistency industry consistency and difficulties it would impose on issuers.  (This decision may be reconsidered in the future.)

<br/> 

### Enforcing valid drug ID
-   Up to now CMS has not been focusing on validation and enforcement of the drug ID field, but is working on improving this area for in the future.

**Comment by dportnoy** [comment]
@BAP-Jeff  Take a look above.  Hopefully, it answers some of your questions.

It would be helpful if you'd like to rename the title of this issue to describe the purpose of the use case.  In other words, to focus on what you wanted to accomplish with the data, rather than just the problems with it.  Thanks.

**Comment by ghost** [comment]
@dportnoy 

I updated the use case name, not the most creative one, but it was what my original purpose was.

As for the Use Case write-up, it is helpful for sure.  I understand this is a process that will improve over time, so I certainly hope at some point someone decides to:
1. Validate drug ids
2. Enforce a drug tier/status nomenclature
3. Not allow restrictions to be optional
4. Add a date to the JSON files, so changes can be detected

I have very much appreciated your help in getting several items addressed.  Does CCIO have a mailbox that issues can be submitted to directly?  I think it is outside your remit to deal with smaller items in the future.

Thanks,

Jeff

**Comment by ghost** [comment]
@dportnoy 

I have been digging in deeper into the Marketplace PUF files specifically the Plan Attributes file.  Given all the work we have done on the Machine Readable file, I was looking to link the two PUF files by IssuerID.  For the most part things connected, but I have found hundreds of records that appear to  have no Formulary records.  Is this anything you heard about or investigated?

If not, let me know, maybe we should open up a new issue.

Thanks,

Jeff

**Comment by dportnoy** [comment]
@BAP-Jeff  Apologies for the delay.  I was out for a couple weeks.  Sure, it would be good if you could post your findings on missing formulary records.  (Note, that dental plans are not expected to have formulary data.)  In general, CCIIO works to help issuers get past common problems.  So my personal opinion is that shining a light on problems could only help improve the data quality over time.

**Comment by dportnoy** [comment]
@BAP-Jeff, let me know if you're comfortable with sharing the aggregated drug formulary dataset.  Take a look at use case #56.

**Comment by ghost** [comment]
Sure, I am happy to help.  I think having some other people looking at this
will help push CCIO to get some fixes happening.

Did you just want me to respond to the thread or post some code?

**Comment by dportnoy** [comment]
@BAP-Jeff, go ahead and join the party over at use case #56.  We have marks, cornstein and ftrotter looking at it.  I'll post the rest there.
